name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          VITE_TEST_TOKEN: ${{ secrets.VITE_TEST_TOKEN }}
          VITE_TEST_ACADEMIC: ${{ secrets.VITE_TEST_ACADEMIC }}
          VITE_TEST_MUSIC: ${{ secrets.VITE_TEST_MUSIC }}
          VITE_TEST_SPORTS: ${{ secrets.VITE_TEST_SPORTS }}
          VITE_LIVE_TOKEN: ${{ secrets.VITE_LIVE_TOKEN }}
          VITE_LIVE_ACADEMIC: ${{ secrets.VITE_LIVE_ACADEMIC }}
          VITE_LIVE_MUSIC: ${{ secrets.VITE_LIVE_MUSIC }}
          VITE_LIVE_SPORTS: ${{ secrets.VITE_LIVE_SPORTS }}
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
